// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEfLw5m9PcC4tHllPSK5aItiw_DniWeOY',
    appId: '1:163645915412:web:b938f115e081158f8f0201',
    messagingSenderId: '163645915412',
    projectId: 'test-56b2b',
    authDomain: 'test-56b2b.firebaseapp.com',
    databaseURL: 'https://test-56b2b-default-rtdb.firebaseio.com',
    storageBucket: 'test-56b2b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_npYrd7jAaq-_XIA5hbJz8hXE5iPKvAk',
    appId: '1:163645915412:android:ab265c50b7eb57bf8f0201',
    messagingSenderId: '163645915412',
    projectId: 'test-56b2b',
    databaseURL: 'https://test-56b2b-default-rtdb.firebaseio.com',
    storageBucket: 'test-56b2b.firebasestorage.app',
  );



  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVln8oMxHpw3M8UCqxtvnYgEXOdW53rCk',
    appId: '1:163645915412:ios:005d4d63c3ffe75b8f0201',
    messagingSenderId: '163645915412',
    projectId: 'test-56b2b',
    databaseURL: 'https://test-56b2b-default-rtdb.firebaseio.com',
    storageBucket: 'test-56b2b.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVln8oMxHpw3M8UCqxtvnYgEXOdW53rCk',
    appId: '1:163645915412:ios:005d4d63c3ffe75b8f0201',
    messagingSenderId: '163645915412',
    projectId: 'test-56b2b',
    databaseURL: 'https://test-56b2b-default-rtdb.firebaseio.com',
    storageBucket: 'test-56b2b.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEfLw5m9PcC4tHllPSK5aItiw_DniWeOY',
    appId: '1:163645915412:web:e39dcb3157f70b898f0201',
    messagingSenderId: '163645915412',
    projectId: 'test-56b2b',
    authDomain: 'test-56b2b.firebaseapp.com',
    databaseURL: 'https://test-56b2b-default-rtdb.firebaseio.com',
    storageBucket: 'test-56b2b.firebasestorage.app',
  );
}
